### ISSUE TITLE
Consistencia entre modelo y data

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-11#11]
está bien considerar esto el módelo pero también está bien que products esté en data. Lo que tienen que hacer es decidir en que lado ponen ambos ya que son similares y no deberían estar tan separados. 

https://github.com/0623CIFSNCN05LAED/grupo-11/blob/1cf7abe536426524aeadb994016724def1df23ea/src/models/User.js#L3

**Comment by LautaroRe01** [comment]
Esta bien como lo tenemos ahora? Porque no entendemos a que te referis.
