### ISSUE TITLE
Funcionalidad de sesión

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-11#15]
Si bien el primer paso posterior al login parece llevar al perfil de un usuario, realmente está funcionando muy mal la parte del login, el header no da cuenta de que haya cambiado algo, pues los botones de login y crear una cuenta siguen ahí, y si sales de la página del perfil pareciera no haber ninguna forma de volver al perfil mas allá de loguearte de nuevo.
A su vez, el enlace de crear productos queda completamente inaccesible ya que en ningún momento se puede acceder a este enlace (el middleware está fallando constantemente)

**Comment by camilamzc94** [comment]
listo ailu, ahi modificamos
