### ISSUE TITLE
Middleware de login repetido o erróneo

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-11#17]
Este middleware que se encuentra en `userLogin` utiliza la propiedad `req.session.login`, pero es la única vez en todo el proyecto que se hace referencia a dicha propiedad, por lo que nunca dejaría pasar al usuario. (Lo que actualmente afecta a una ruta)
https://github.com/0623CIFSNCN05LAED/grupo-11/blob/b0f39507f06f0e78a7f22fec6ba4a71ad91b664e/src/middledware/userLogin.js#L2-L6
La funcionalidad parece ser la que el `authMiddleware` ya se encarga de realizar, por lo que sugeriría una revisión allí.

**Comment by leandroheffes24** [comment]
Solucionado.
