### ISSUE TITLE
Presencia parcial de la función de recordar usuario

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-11#18]
Si bien es un punto opcional, estaría bueno que en caso de estar guardando la cookie que permitiría la funcionalidad de recordar
https://github.com/0623CIFSNCN05LAED/grupo-11/blob/b0f39507f06f0e78a7f22fec6ba4a71ad91b664e/src/controllers/user-controller.js#L39
Pudieran finalizar su desarrollo con el middleware que complementaría dicha funcionalidad.

**Comment by camilamzc94** [comment]
listo!!
