### ISSUE TITLE
División de entornos

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-11#19]
Como sugerencia, podría serles productivo ya dividir las rutas por el entorno en el que operan.
Es decir, tener las rutas de usuarios y las de productos separadas, como si ya tienen los controladores. (Estos pudiendo unirse con un main router, por ejemplo).
La sugerencia parte luego de analizar la cantidad de rutas que posee sueltas un mismo archivo, sobretodo en este punto.
https://github.com/0623CIFSNCN05LAED/grupo-11/blob/b0f39507f06f0e78a7f22fec6ba4a71ad91b664e/src/routes/main-router.js#L42-L67

**Comment by leandroheffes24** [comment]
Realizamos la corrección. Esperamos la revisión.
