### ISSUE TITLE
Revisar modelos de usuarios y productos

### ISSUE THREAD

**Issue by jamaneffa** [0623CIFSNCN05LAED/grupo-11#25]
Falta definir el campo id en los modelos (hay q definirlo como autoincremental en la base de datos y setearlo de la misma forma en el modelo)

**Comment by LautaroRe01** [comment]
El Id no esta definido en el modelo, pero funciona en la Base de Datos. y es autoincremental. Lo dejamos asi?

**Comment by jamaneffa** [comment]
En el modelo debe estar definido tal cual está en la base de datos. Puede funcionar. Pero no es lo correcto
