### ISSUE TITLE
Manejo de imagenes

### ISSUE THREAD

**Issue by jamaneffa** [0623CIFSNCN05LAED/grupo-11#26]
Modificar servicios y controladores de usuarios y productos para que suba correctamente la imagen y se pueda visualizar en la vista de perfil.

Tip: al servicio deberían pasarle como parámetro un archivo además del "nuevoUsuario" que están usando. (Podrían usar body y file para ser mas claros).  y cuando lo llaman en el controlador le pasan el req.body y el req.file

**Comment by LautaroRe01** [comment]
Resuelto.
