### ISSUE TITLE
Base de Datos

### ISSUE THREAD

**Issue by jamaneffa** [0623CIFSNCN05LAED/grupo-11#27]
El shopping_cart debería solo tener el id de usuario (y cualquier otro dato que crean conveniente, cómo la fechad e creación por ejemplo) y podríamos cargar toda la informacion de los productos en la tabla products_shopping_cart	

Podrían agregar una tabla de categorías y/o marcas.

**Comment by LautaroRe01** [comment]
Resuelto.
