### ISSUE TITLE
Separacion de archivos

### ISSUE THREAD

**Issue by jamaneffa** [0623CIFSNCN05LAED/grupo-11#28]
Tienen todos los archivos de servicios en una carpeta llamada productServices.

**Comment by LautaroRe01** [comment]
Para cambiar el nombre y que lo cambie en todos los lados donde fue requerido, como hacemos?

**Comment by jamaneffa** [comment]
Hay extensiónes de VSC que sirven para eso por ejemplo una opción es "Rename Symbol" q la he usado hace un tiempo no se si segura funcionado. De todas formas me refería más a q tengan una carpeta llamada services y dentro de ella dos archivos distintos para productos y usuarios
