### ISSUE TITLE
Separar rutas

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-11#7]
Al tener todo en un mismo módulo de rutas no están aprovechando modularizar el código y hacerlo más mantenible y escalable

https://github.com/0623CIFSNCN05LAED/grupo-11/blob/1cf7abe536426524aeadb994016724def1df23ea/src/routes/main-router.js#L64-L74

**Comment by camilamzc94** [comment]
listo luis! ya lo abrimos. dejo abierto, cualquier cosa nos avisas
